### ISSUE TITLE
Example Cholesky does not compile

### ISSUE THREAD

**Issue by cogumbreiro** [habanero-rice/cnc-framework#11]
I am having problems compiling the Cholesky example.
Environment: icnc 1.0.100, tbb42, gcc-4.9, Ubuntu 17.04.
```
$ make
cc -O2 -g -DCNC_DEBUG -I. -I./cnc_support/icnc  -Wall -pthread -Wno-unused-variable -c Main.c -o build/icnc/Main.o
cc -O2 -g -DCNC_DEBUG -I. -I./cnc_support/icnc  -Wall -pthread -Wno-unused-variable -c Cholesky.c -o build/icnc/Cholesky.o
Cholesky.c: In function ‘Cholesky_cncInitialize’:
Cholesky.c:14:27: error: ‘tileCount’ undeclared (first use in this function)
         for (_j = 0; _j < tileCount; _j++) {
                           ^~~~~~~~~
Cholesky.c:14:27: note: each undeclared identifier is reported only once for each function it appears in
Makefile:104: recipe for target 'build/icnc/Cholesky.o' failed
make: *** [build/icnc/Cholesky.o] Error 1
```

**Comment by DaoWen** [comment]
Which version of Cholesky are you compiling? The README explains that there are two versions in two sub-directories: `generated_input` and `file_input`. It looks to me like you tried to compile the files in the `common` sub-directory, which is an incomplete set of files that are common among the two projects. (And since the project is incomplete, you're getting an error.)

**Comment by cogumbreiro** [comment]
You got it. I was trying to compile Cholesky in the `common` directory.

Sorry about the noise!

**Comment by DaoWen** [comment]
No problem! These reports are still helpful. I just pushed a change to cause `make` to fail in the `Cholesky/common/` subdirectory: e71179f4ee7a4a049627a1ac96502a4a80a6c5a2

**Comment by cogumbreiro** [comment]
Great idea! Way better UX.
